version: '3'
services:
#mssql docker
  eprodaja-sqlib170007:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    networks:
      - eprodajanet

  eprodaja-apiib170007:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:DefaultConnection=Server=eprodaja-sql,1433;Database=eprodaja-sqlib170007;User=sa;Password=QWElkj132!;ConnectRetryCount=0
    ports:
      - 5010:5010
    networks:
      - eprodajanet      
    links:
      - eprodaja-sqlib170007
    depends_on:
      - eprodaja-sqlib170007
      
networks:
  eprodajanet:
    driver: bridge      